import = [
  "~/.dotfiles/config/alacritty/theme-active.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "ExtraLight"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_title = true
opacity = 0.98
blur = true

[window.dimensions]
columns = 200
lines = 75

[window.padding]
x = 5
y = 5
