# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/a.usage.kdl
_a()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in a." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_a.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name a
bin a
version "1.1.0"
about "Encrypt and decrypt files or directories with age and SSH keys"
flag "-v --verbose" help="Print log messages to console"
flag --delete help="Delete original files after encryption"
flag "-f --force" help="Overwrite existing output files"
cmd encrypt help="Encrypt a file or directory" {
    alias e enc
    arg <target> help="File or directory to encrypt"
}
cmd decrypt help="Decrypt a file or directory" {
    alias d dec
    arg <target> help="File or directory to decrypt"
}
cmd help help="Show help"
cmd version help="Show version"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _a a
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _a a
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
