# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/dfm.usage.kdl
_dfm()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in dfm." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_dfm.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name dfm
bin dfm
author "Ismo Vuorinen"
about "Dotfiles manager and install helper"
cmd install help="Install tools, packages, and configurations" {
    cmd all help="Install everything in the correct order"
    cmd apt-packages help="Install apt packages (Debian/Ubuntu)"
    cmd cheat-databases help="Install cheat external cheatsheet databases"
    cmd composer help="Install PHP Package Manager Composer"
    cmd dnf-packages help="Install dnf packages (Fedora/RHEL)"
    cmd fonts help="Install programming fonts"
    cmd gh help="Install GitHub CLI Extensions"
    cmd git-crypt help="Install git-crypt from source"
    cmd imagick help="Install ImageMagick CLI"
    cmd macos help="Setup nice macOS defaults"
    cmd mise help="Install tools via mise (runtimes + CLI tools)"
    cmd mise-cleanup help="Remove old version manager installations" {
        flag --dry-run help="Show what would be removed without removing"
    }
    cmd ntfy help="Install ntfy notification tool"
    cmd python-libs help="Install Python libraries (libtmux, pynvim)"
    cmd shellspec help="Install shellspec testing framework"
    cmd xcode-cli-tools help="Install Xcode CLI tools (macOS)"
    cmd z help="Install z directory jumper"
}
cmd brew help="Homebrew package management" {
    cmd install help="Install packages from Brewfile"
    cmd update help="Update Homebrew and packages"
    cmd updatebundle help="Update Brewfile with descriptions"
    cmd autoupdate help="Setup Homebrew auto-update"
    cmd leaves help="List installed-on-request packages"
    cmd clean help="Cleanup old versions"
    cmd untracked help="List packages not in Brewfile"
}
cmd apt help="APT package management (Debian/Ubuntu)" {
    cmd upkeep help="Full maintenance (update + upgrade + autoremove + clean)"
    cmd install help="Install packages from apt.txt"
    cmd update help="Update package lists"
    cmd upgrade help="Upgrade installed packages"
    cmd autoremove help="Remove unused packages"
    cmd clean help="Clean package cache"
}
cmd check help="System information checks" {
    cmd arch help="Get or check current architecture" {
        alias a
        arg "[arch]" help="Architecture to check against" required=#false
    }
    cmd host help="Get or check current hostname" {
        alias h hostname
        arg "[hostname]" help="Hostname to check against" required=#false
    }
}
cmd dotfiles help="Format and reset configurations" {
    cmd fmt help="Run all formatters"
    cmd yamlfmt help="Format YAML files"
    cmd shfmt help="Format shell scripts"
    cmd reset_all help="Reset everything"
    cmd reset_nvim help="Reset neovim state and config"
}
cmd helpers help="Display system information" {
    cmd aliases help="Show shell aliases" {
        arg <shell> help="Shell to show aliases for (bash, zsh, fish)"
    }
    cmd colors help="Show 256 terminal colors"
    cmd env help="Show environment variables"
    cmd functions help="Show shell functions"
    cmd nvim help="Show neovim keybindings"
    cmd path help="Show PATH directories"
    cmd tmux help="Show tmux keybindings"
    cmd wezterm help="Show wezterm keybindings"
}
cmd docs help="Generate documentation" {
    cmd all help="Update all keybindings docs"
    cmd tmux help="Update tmux keybindings"
    cmd nvim help="Update nvim keybindings"
    cmd wezterm help="Update wezterm keybindings"
}
cmd scripts help="Run install scripts from scripts/" {
    arg "[script]" help="Script name to run (without install- prefix)" required=#false
}
cmd tests help="Test visualization helpers" {
    cmd msgr help="Show all msgr message types"
    cmd params help="List all parameters"
}
cmd help help="Show help"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _dfm dfm
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _dfm dfm
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
