# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/git-attributes.usage.kdl
_git_attributes()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in git-attributes." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_git_attributes.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name git-attributes
bin git-attributes
about "Check .gitattributes coverage and suggest missing rules"
flag "-h --help" help="Show help"
flag "-v --verbose" help="Verbose output"
flag "-e --exit" help="Exit with error if uncovered files found"
flag "-p --pattern" help="Show pattern matches"
flag "-n --no-suggest" help="Skip suggestions"
flag "-w --write" help="Write suggested rules to .gitattributes"
flag "-f --format-width" help="Format column width" {
    arg <width>
}
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _git_attributes git-attributes
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _git_attributes git-attributes
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
