# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/git-update-dirs.usage.kdl
_git_update_dirs()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in git-update-dirs." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_git_update_dirs.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name git-update-dirs
bin git-update-dirs
about "Pull and rebase all git repos in subdirectories"
flag --help help="Display help"
flag --version help="Display version"
flag "-v --verbose" help="Verbose output"
flag "-q --quiet" help="Quiet output"
flag --force help="Force operations"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _git_update_dirs git-update-dirs
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _git_update_dirs git-update-dirs
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
