# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/install-ntfy.sh.usage.kdl
_install_ntfy_sh()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in install-ntfy.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_install_ntfy_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name install-ntfy.sh
bin install-ntfy.sh
about "Install ntfy notification tool"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _install_ntfy_sh install-ntfy.sh
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _install_ntfy_sh install-ntfy.sh
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
