# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/msgr.usage.kdl
_msgr()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in msgr." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_msgr.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name msgr
bin msgr
about "Colored message output helper for shell scripts"
cmd msg help="Print a message with arrow marker" {
    arg <message> help="Message text"
}
cmd yay help="Print a celebration message" {
    arg <message> help="Message text"
}
cmd yay_done help="Print a celebration with checkmark" {
    arg <message> help="Message text"
}
cmd done help="Print a completion checkmark" {
    arg <message> help="Message text"
}
cmd run help="Print a running-task message" {
    arg <message> help="Message text"
}
cmd run_done help="Print a running-task with checkmark" {
    arg <message> help="Message text"
}
cmd ok help="Print a success message" {
    arg <message> help="Message text"
}
cmd warn help="Print a warning message" {
    arg <message> help="Message text"
}
cmd err help="Print an error message" {
    arg <message> help="Message text"
}
cmd prompt help="Print a prompt-style message" {
    arg <message> help="Message text"
}
cmd prompt_done help="Print a prompt with checkmark" {
    arg <message> help="Message text"
}
cmd nested help="Print an indented message" {
    arg <message> help="Message text"
}
cmd nested_done help="Print an indented message with checkmark" {
    arg <message> help="Message text"
}
cmd test help="Show all message types"
cmd help help="Show help"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _msgr msgr
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _msgr msgr
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
