# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/php-switcher.usage.kdl
_php_switcher()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in php-switcher." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_php_switcher.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name php-switcher
bin php-switcher
about "Switch between PHP versions installed via Homebrew"
flag --help help="Show help"
flag --installed help="List installed PHP versions"
flag --current help="Show currently active version"
flag --auto help="Auto-switch based on .php-version file"
arg "[version]" help="PHP version (e.g., 7.4, 8.0) or 'latest'" required=#false
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _php_switcher php-switcher
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _php_switcher php-switcher
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
