# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/pushover.usage.kdl
_pushover()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in pushover." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_pushover.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name pushover
bin pushover
about "Send Pushover notifications from the command line"
flag -c help="Callback URL" {
    arg <callback>
}
flag -d help="Target device" {
    arg <device>
}
flag -D help="Delivery timestamp" {
    arg <timestamp>
}
flag -e help="Expiration time in seconds" {
    arg <expire>
}
flag -p help="Priority level (-2 to 2)" {
    arg <priority>
}
flag -r help="Retry interval in seconds" {
    arg <retry>
}
flag -t help="Message title" {
    arg <title>
}
flag -T help="Pushover API token" {
    arg <token>
}
flag -s help="Notification sound" {
    arg <sound>
}
flag -u help="URL to include" {
    arg <url>
}
flag -U help="Pushover user key" {
    arg <user>
}
flag -a help="URL title" {
    arg <url_title>
}
arg <message> help="Message content"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _pushover pushover
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _pushover pushover
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
