# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-codeql.usage.kdl
_x_codeql()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-codeql." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_codeql.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name x-codeql
bin x-codeql
about "CodeQL security scanning wrapper"
flag --path help="Source path to analyze (default: current directory)" {
    arg <path>
}
flag --parallel help="Run language analyses in parallel"
flag "-h --help" help="Show help"
flag "-v --version" help="Show version"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _x_codeql x-codeql
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _x_codeql x-codeql
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
