# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-foreach.usage.kdl
_x_foreach()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-foreach." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_foreach.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name x-foreach
bin x-foreach
about "Run a command in each directory from a listing"
arg <listing_cmd> help="Command that lists directories"
arg <command>… help="Command to run in each directory" var=#true
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _x_foreach x-foreach
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _x_foreach x-foreach
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
