# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-path.usage.kdl
_x_path()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-path." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_path.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name x-path
bin x-path
about "Unified PATH manipulation tool"
cmd append help="Append directory to PATH" {
    arg <directory> help="Directory to append"
}
cmd prepend help="Prepend directory to PATH" {
    arg <directory> help="Directory to prepend"
}
cmd remove help="Remove directory from PATH" {
    arg <directory> help="Directory to remove"
}
cmd check help="Check if directory is in PATH" {
    arg <directory> help="Directory to check"
}
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _x_path x-path
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _x_path x-path
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
