# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-sonarcloud.usage.kdl
_x_sonarcloud()
{
  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-sonarcloud." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local cur prev words cword was_split comp_args
  _comp_initialize -n : -- "$@" || return
  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_sonarcloud.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name x-sonarcloud
bin x-sonarcloud
about "Fetch SonarCloud issues for LLM analysis"
flag --pr help="PR-specific issues" {
    arg <number>
}
flag --branch help="Branch-specific issues" {
    arg <name>
}
flag --org help="Organization name" {
    arg <org>
}
flag --project-key help="Project key" {
    arg <key>
}
flag --severities help="Filter by severity (BLOCKER,CRITICAL,MAJOR,MINOR,INFO)" {
    arg <severities>
}
flag --types help="Filter by type (BUG,VULNERABILITY,CODE_SMELL,SECURITY_HOTSPOT)" {
    arg <types>
}
flag --statuses help="Filter by status (OPEN,CONFIRMED,REOPENED)" {
    arg <statuses>
}
flag --resolved help="Include resolved issues"
flag "-h --help" help="Show help"
__USAGE_EOF__
  # shellcheck disable=SC2207
  _comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
  _comp_ltrim_colon_completions "$cur"
  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]]; then
    unset COMPREPLY
  fi
  return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
  shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _x_sonarcloud x-sonarcloud
else
  shopt -u hostcomplete && complete -o nospace -o bashdefault -F _x_sonarcloud x-sonarcloud
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
