# Lakka zsh configuration.
#
# shellcheck shell=bash

# Explicitely set XDG Folders
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_BIN_HOME="$HOME/.local/bin" # this one is custom

export PATH="$XDG_BIN_HOME:$HOME/bin:$HOME/.gem/bin:$HOME/.rvm/bin:/usr/local/bin:/usr/sbin:/usr/bin:$PATH"
export LC_ALL=fi_FI.utf8

[[ -f "$XDG_BIN_HOME/antigen.zsh" ]] && source "$XDG_BIN_HOME/antigen.zsh"

# If antigen was loadeded
if command -v antigen &> /dev/null; then
  antigen use oh-my-zsh

  hash git 2>/dev/null && antigen bundle git
  hash php 2>/dev/null && antigen bundle php

  antigen bundle autojump
  antigen bundle command-not-found
  antigen bundle jreese/zsh-titles
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-completions
  antigen bundle unixorn/rvm-plugin
  antigen bundle unixorn/autoupdate-antigen.zshplugin

  antigen theme oskarkrawczyk/honukai-iterm-zsh honukai

  antigen apply
fi

alias t='tail -f'
alias logrotate='/usr/sbin/logrotate -s $HOME/logs/state'
alias dn='du -chd1'
alias nano='nano -wS -$'
alias gpg=gpg2

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" ]] # Load RVM into a shell session *as a function*
. "$HOME/.acme.sh/acme.sh.env"
