version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update Git Submodules daily
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /
