#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  --plugin-dir=dotbot-brew \
  --plugin-dir=dotbot-gh-extension \
  --plugin-dir=dotbot-golang \
  --plugin-dir=dotbot-if \
  --plugin-dir=dotbot-ifplatform \
  -c "${CONFIG}" \
  "${@}"
