#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_BIN_PATH="${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${DOTBOT_BIN_PATH}" \
  -d "${BASEDIR}" \
  -c "${CONFIG}" \
  "${@}"

