[metadata]
name = "dirs"
description = "Select from directories"
requirements = ["fd", "eza"]

[source]
command = ["fd -t d", "fd -t d --hidden"]

[preview]
command = "eza -la --color=always '{}'"

[keybindings]
shortcut = "f2"
ctrl-s = "cycle_sources"

[actions.cd]
description = "Open a shell in the selected directory"
command = "cd '{}' && $SHELL"
mode = "execute"
