return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "comment",
      "diff",
      "dockerfile",
      "gitignore",
      "graphql",
      "html",
      "javascript",
      "json",
      "json5",
      "latex",
      "lua",
      "markdown",
      "php",
      "phpdoc",
      "python",
      "scss",
      "terraform",
      "todotxt",
      "toml",
      "typescript",
      "vim",
      "vue",
      "yaml",
    },
  },
}
