---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.331.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli
  version: 'v2.69.0'
- name: junegunn/fzf
  version: 'v0.60.3'
- name: jqlang/jq
  version: 'jq-1.7.1'
- name: 1password/cli
  version: '2.30.3'
