#!/usr/bin/env bash
# shellcheck shell=bash
# vim: filetype=zsh

export DOTFILES="$HOME/.dotfiles"
source "$DOTFILES/scripts/shared.sh"
path_prepend "$DOTFILES/local/bin"

# Explicitly set XDG folders
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# custom variables
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$HOME/.local/run"

path_append "/opt/homebrew/bin"
have brew && eval "$(brew shellenv)"

path_append "/usr/local/bin"
path_prepend "$XDG_BIN_HOME"

source "$DOTFILES/config/exports-shell"
source "$DOTFILES/config/exports-apps"

have nvim && export EDITOR="nvim"
