#!/bin/sh
#
# Usage:
#
#    sh install-dotfiles.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install-dotfiles.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "$HOME/.dotfiles/bash_profile" "$HOME/.bash_profile"
handle_file_ln "$HOME/.dotfiles/bashrc" "$HOME/.bashrc"
handle_file_ln "$HOME/.dotfiles/config/alias" "$HOME/.config/alias"
handle_file_ln "$HOME/.dotfiles/config/exports" "$HOME/.config/exports"
handle_file_ln "$HOME/.dotfiles/config/flipperdevices.com/qFlipper.ini" "$HOME/.config/flipperdevices.com/qFlipper.ini"
handle_file_ln "$HOME/.dotfiles/config/functions" "$HOME/.config/functions"
handle_file_ln "$HOME/.dotfiles/config/gh/config.yml" "$HOME/.config/gh/config.yml"
handle_file_ln "$HOME/.dotfiles/config/git/config" "$HOME/.config/git/config"
handle_file_ln "$HOME/.dotfiles/config/git/gitignore" "$HOME/.config/git/gitignore"
handle_file_ln "$HOME/.dotfiles/config/nvim/LICENSE" "$HOME/.config/nvim/LICENSE"
handle_file_ln "$HOME/.dotfiles/config/nvim/colors/default_theme.lua" "$HOME/.config/nvim/colors/default_theme.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/config.ld" "$HOME/.config/nvim/config.ld"
handle_file_ln "$HOME/.dotfiles/config/nvim/init.lua" "$HOME/.config/nvim/init.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/Comment.lua" "$HOME/.config/nvim/lua/configs/Comment.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/aerial.lua" "$HOME/.config/nvim/lua/configs/aerial.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/alpha.lua" "$HOME/.config/nvim/lua/configs/alpha.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/autopairs.lua" "$HOME/.config/nvim/lua/configs/autopairs.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/better_escape.lua" "$HOME/.config/nvim/lua/configs/better_escape.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/bufferline.lua" "$HOME/.config/nvim/lua/configs/bufferline.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/cmp.lua" "$HOME/.config/nvim/lua/configs/cmp.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/colorizer.lua" "$HOME/.config/nvim/lua/configs/colorizer.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/dap.lua" "$HOME/.config/nvim/lua/configs/dap.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/dapui.lua" "$HOME/.config/nvim/lua/configs/dapui.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/dressing.lua" "$HOME/.config/nvim/lua/configs/dressing.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/gitsigns.lua" "$HOME/.config/nvim/lua/configs/gitsigns.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/heirline.lua" "$HOME/.config/nvim/lua/configs/heirline.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/indent-line.lua" "$HOME/.config/nvim/lua/configs/indent-line.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/indent-o-matic.lua" "$HOME/.config/nvim/lua/configs/indent-o-matic.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/lspconfig.lua" "$HOME/.config/nvim/lua/configs/lspconfig.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/lspkind.lua" "$HOME/.config/nvim/lua/configs/lspkind.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/luasnip.lua" "$HOME/.config/nvim/lua/configs/luasnip.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/mason-lspconfig.lua" "$HOME/.config/nvim/lua/configs/mason-lspconfig.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/mason-null-ls.lua" "$HOME/.config/nvim/lua/configs/mason-null-ls.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/mason-nvim-dap.lua" "$HOME/.config/nvim/lua/configs/mason-nvim-dap.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/mason.lua" "$HOME/.config/nvim/lua/configs/mason.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/neo-tree.lua" "$HOME/.config/nvim/lua/configs/neo-tree.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/notify.lua" "$HOME/.config/nvim/lua/configs/notify.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/null-ls.lua" "$HOME/.config/nvim/lua/configs/null-ls.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/nvim-web-devicons.lua" "$HOME/.config/nvim/lua/configs/nvim-web-devicons.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/server-settings/jsonls.lua" "$HOME/.config/nvim/lua/configs/server-settings/jsonls.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/server-settings/sumneko_lua.lua" "$HOME/.config/nvim/lua/configs/server-settings/sumneko_lua.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/session_manager.lua" "$HOME/.config/nvim/lua/configs/session_manager.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/smart-splits.lua" "$HOME/.config/nvim/lua/configs/smart-splits.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/telescope.lua" "$HOME/.config/nvim/lua/configs/telescope.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/toggleterm.lua" "$HOME/.config/nvim/lua/configs/toggleterm.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/treesitter.lua" "$HOME/.config/nvim/lua/configs/treesitter.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/which-key-register.lua" "$HOME/.config/nvim/lua/configs/which-key-register.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/which-key.lua" "$HOME/.config/nvim/lua/configs/which-key.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/configs/window-picker.lua" "$HOME/.config/nvim/lua/configs/window-picker.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/autocmds.lua" "$HOME/.config/nvim/lua/core/autocmds.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/bootstrap.lua" "$HOME/.config/nvim/lua/core/bootstrap.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/diagnostics.lua" "$HOME/.config/nvim/lua/core/diagnostics.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/icons/nerd_font.lua" "$HOME/.config/nvim/lua/core/icons/nerd_font.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/icons/text.lua" "$HOME/.config/nvim/lua/core/icons/text.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/mappings.lua" "$HOME/.config/nvim/lua/core/mappings.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/options.lua" "$HOME/.config/nvim/lua/core/options.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/plugins.lua" "$HOME/.config/nvim/lua/core/plugins.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/git.lua" "$HOME/.config/nvim/lua/core/utils/git.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/init.lua" "$HOME/.config/nvim/lua/core/utils/init.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/lsp.lua" "$HOME/.config/nvim/lua/core/utils/lsp.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/mason.lua" "$HOME/.config/nvim/lua/core/utils/mason.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/status.lua" "$HOME/.config/nvim/lua/core/utils/status.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/ui.lua" "$HOME/.config/nvim/lua/core/utils/ui.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/core/utils/updater.lua" "$HOME/.config/nvim/lua/core/utils/updater.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/base.lua" "$HOME/.config/nvim/lua/default_theme/base.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/colors.lua" "$HOME/.config/nvim/lua/default_theme/colors.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/init.lua" "$HOME/.config/nvim/lua/default_theme/init.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/lsp.lua" "$HOME/.config/nvim/lua/default_theme/lsp.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/aerial.lua" "$HOME/.config/nvim/lua/default_theme/plugins/aerial.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/beacon.lua" "$HOME/.config/nvim/lua/default_theme/plugins/beacon.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/bufferline.lua" "$HOME/.config/nvim/lua/default_theme/plugins/bufferline.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/cmp.lua" "$HOME/.config/nvim/lua/default_theme/plugins/cmp.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/dapui.lua" "$HOME/.config/nvim/lua/default_theme/plugins/dapui.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/dashboard.lua" "$HOME/.config/nvim/lua/default_theme/plugins/dashboard.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/gitsigns.lua" "$HOME/.config/nvim/lua/default_theme/plugins/gitsigns.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/highlighturl.lua" "$HOME/.config/nvim/lua/default_theme/plugins/highlighturl.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/hop.lua" "$HOME/.config/nvim/lua/default_theme/plugins/hop.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/indent_blankline.lua" "$HOME/.config/nvim/lua/default_theme/plugins/indent_blankline.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/lightspeed.lua" "$HOME/.config/nvim/lua/default_theme/plugins/lightspeed.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/neo-tree.lua" "$HOME/.config/nvim/lua/default_theme/plugins/neo-tree.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/notify.lua" "$HOME/.config/nvim/lua/default_theme/plugins/notify.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/nvim-tree.lua" "$HOME/.config/nvim/lua/default_theme/plugins/nvim-tree.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/nvim-web-devicons.lua" "$HOME/.config/nvim/lua/default_theme/plugins/nvim-web-devicons.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/rainbow.lua" "$HOME/.config/nvim/lua/default_theme/plugins/rainbow.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/symbols_outline.lua" "$HOME/.config/nvim/lua/default_theme/plugins/symbols_outline.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/telescope.lua" "$HOME/.config/nvim/lua/default_theme/plugins/telescope.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/treesitter.lua" "$HOME/.config/nvim/lua/default_theme/plugins/treesitter.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/vimwiki.lua" "$HOME/.config/nvim/lua/default_theme/plugins/vimwiki.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/default_theme/plugins/which-key.lua" "$HOME/.config/nvim/lua/default_theme/plugins/which-key.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/lua/user_example/init.lua" "$HOME/.config/nvim/lua/user_example/init.lua"
handle_file_ln "$HOME/.dotfiles/config/nvim/packer_snapshot" "$HOME/.config/nvim/packer_snapshot"
handle_file_ln "$HOME/.dotfiles/config/starship.toml" "$HOME/.config/starship.toml"
handle_file_ln "$HOME/.dotfiles/config/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"
handle_file_ln "$HOME/.dotfiles/config/wtf/config.yml" "$HOME/.config/wtf/config.yml"
handle_file_ln "$HOME/.dotfiles/ecrc" "$HOME/.ecrc"
handle_file_ln "$HOME/.dotfiles/git_profiles" "$HOME/.git_profiles"
handle_file_ln "$HOME/.dotfiles/huskyrc" "$HOME/.huskyrc"
handle_file_ln "$HOME/.dotfiles/local/bin/antigen.zsh" "$HOME/.local/bin/antigen.zsh"
handle_file_ln "$HOME/.dotfiles/local/bin/dfm" "$HOME/.local/bin/dfm"
handle_file_ln "$HOME/.dotfiles/local/bin/git-dirty" "$HOME/.local/bin/git-dirty"
handle_file_ln "$HOME/.dotfiles/local/bin/x-check-git-attributes" "$HOME/.local/bin/x-check-git-attributes"
handle_file_ln "$HOME/.dotfiles/local/bin/x-dupes.pl" "$HOME/.local/bin/x-dupes.pl"
handle_file_ln "$HOME/.dotfiles/local/bin/x-foreach" "$HOME/.local/bin/x-foreach"
handle_file_ln "$HOME/.dotfiles/local/bin/x-multi-ping.pl" "$HOME/.local/bin/x-multi-ping.pl"
handle_file_ln "$HOME/.dotfiles/local/bin/x-open-ports" "$HOME/.local/bin/x-open-ports"
handle_file_ln "$HOME/.dotfiles/local/bin/x-ssl-expiry-date" "$HOME/.local/bin/x-ssl-expiry-date"
handle_file_ln "$HOME/.dotfiles/local/bin/x-until-error" "$HOME/.local/bin/x-until-error"
handle_file_ln "$HOME/.dotfiles/local/bin/x-until-success" "$HOME/.local/bin/x-until-success"
handle_file_ln "$HOME/.dotfiles/local/bin/x-when-down" "$HOME/.local/bin/x-when-down"
handle_file_ln "$HOME/.dotfiles/local/bin/x-when-up" "$HOME/.local/bin/x-when-up"
handle_file_ln "$HOME/.dotfiles/rcrc" "$HOME/.rcrc"
handle_file_ln "$HOME/.dotfiles/ssh/allowed_signers" "$HOME/.ssh/allowed_signers"
handle_file_ln "$HOME/.dotfiles/ssh/config" "$HOME/.ssh/config"
handle_file_ln "$HOME/.dotfiles/vuerc" "$HOME/.vuerc"
handle_file_ln "$HOME/.dotfiles/zshrc" "$HOME/.zshrc"
