# this is my bashrc config. there are many like it, but this one is mine.
# shellcheck shell=bash

export DOTFILES="$HOME/.dotfiles"
export PATH="$HOME/.local/bin:$DOTFILES/local/bin:$PATH"
export SHARED_SCRIPTS_SOURCED=0

source "$DOTFILES/config/shared.sh"

# shellcheck source=../config/fzf/fzf.bash
[ -f "${DOTFILES}/config/fzf/fzf.bash" ] &&
  source "${DOTFILES}/config/fzf/fzf.bash"

# Import ssh keys in keychain
ssh-add -A 2>/dev/null

x-have oh-my-posh && {
  eval "$(oh-my-posh init bash --config "$DOTFILES/config/omp/own.toml")"
}

. "$XDG_BIN_HOME/asdf/asdf.sh"
. "$XDG_BIN_HOME/asdf/completions/asdf.bash"

x-have antidot && {
  eval "$(antidot init)"
}
