# this is my zsh config. there are many like it, but this one is mine.
# shellcheck shell=bash

autoload -U colors zsh/terminfo
colors

# Defaults
export DOTFILES="$HOME/.dotfiles"

# Run x-load-configs in your terminal to reload the files.
function x-load-configs()
{
  # Load the shell dotfiles, and then some:
  for file in $DOTFILES/config/{exports,alias,functions}; do
    [ -f "$file" ] && source "$file"
    [ -f "$file-secret" ] && source "$file-secret"
    [ -f "$file-$HOSTNAME" ] && source "$file-$HOSTNAME"
    [ -f "$file-$HOSTNAME-secret" ] && source "$file-$HOSTNAME-secret"
  done
}
x-load-configs

# Import ssh keys in keychain
ssh-add -A 2>/dev/null;

# Try to load antigen, if present
ANTIGEN_ZSH_PATH="$XDG_BIN_HOME/antigen.zsh"
[[ -f "$ANTIGEN_ZSH_PATH" ]] && source "$ANTIGEN_ZSH_PATH"

# antigen is present
if command -v antigen &> /dev/null; then
  antigen use oh-my-zsh

  # config/functions
  x-default-antigen-bundles

  antigen apply
fi

eval "$(starship init zsh)"
