# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/a.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in a." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_a 'name a
bin a
version "1.1.0"
about "Encrypt and decrypt files or directories with age and SSH keys"
flag "-v --verbose" help="Print log messages to console"
flag --delete help="Delete original files after encryption"
flag "-f --force" help="Overwrite existing output files"
cmd encrypt help="Encrypt a file or directory" {
    alias e enc
    arg <target> help="File or directory to encrypt"
}
cmd decrypt help="Decrypt a file or directory" {
    alias d dec
    arg <target> help="File or directory to decrypt"
}
cmd help help="Show help"
cmd version help="Show version"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_a.spec"
echo $_usage_spec_a >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc a -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc a -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
