# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/git-attributes.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in git-attributes." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_git_attributes 'name git-attributes
bin git-attributes
about "Check .gitattributes coverage and suggest missing rules"
flag "-h --help" help="Show help"
flag "-v --verbose" help="Verbose output"
flag "-e --exit" help="Exit with error if uncovered files found"
flag "-p --pattern" help="Show pattern matches"
flag "-n --no-suggest" help="Skip suggestions"
flag "-w --write" help="Write suggested rules to .gitattributes"
flag "-f --format-width" help="Format column width" {
    arg <width>
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_git_attributes.spec"
echo $_usage_spec_git_attributes >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc git-attributes -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc git-attributes -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
