# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/git-update-dirs.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in git-update-dirs." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_git_update_dirs 'name git-update-dirs
bin git-update-dirs
about "Pull and rebase all git repos in subdirectories"
flag --help help="Display help"
flag --version help="Display version"
flag "-v --verbose" help="Verbose output"
flag "-q --quiet" help="Quiet output"
flag --force help="Force operations"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_git_update_dirs.spec"
echo $_usage_spec_git_update_dirs >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc git-update-dirs -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc git-update-dirs -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
