# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/install-completions.sh.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in install-completions.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_install_completions_sh 'name install-completions.sh
bin install-completions.sh
about "Generate shell completions, markdown docs, and manpages from usage specs"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_install_completions_sh.spec"
echo $_usage_spec_install_completions_sh >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc install-completions.sh -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc install-completions.sh -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
