# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/msgr.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in msgr." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_msgr 'name msgr
bin msgr
about "Colored message output helper for shell scripts"
cmd msg help="Print a message with arrow marker" {
    arg <message> help="Message text"
}
cmd yay help="Print a celebration message" {
    arg <message> help="Message text"
}
cmd yay_done help="Print a celebration with checkmark" {
    arg <message> help="Message text"
}
cmd done help="Print a completion checkmark" {
    arg <message> help="Message text"
}
cmd run help="Print a running-task message" {
    arg <message> help="Message text"
}
cmd run_done help="Print a running-task with checkmark" {
    arg <message> help="Message text"
}
cmd ok help="Print a success message" {
    arg <message> help="Message text"
}
cmd warn help="Print a warning message" {
    arg <message> help="Message text"
}
cmd err help="Print an error message" {
    arg <message> help="Message text"
}
cmd prompt help="Print a prompt-style message" {
    arg <message> help="Message text"
}
cmd prompt_done help="Print a prompt with checkmark" {
    arg <message> help="Message text"
}
cmd nested help="Print an indented message" {
    arg <message> help="Message text"
}
cmd nested_done help="Print an indented message with checkmark" {
    arg <message> help="Message text"
}
cmd test help="Show all message types"
cmd help help="Show help"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_msgr.spec"
echo $_usage_spec_msgr >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc msgr -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc msgr -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
