# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/php-switcher.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in php-switcher." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_php_switcher 'name php-switcher
bin php-switcher
about "Switch between PHP versions installed via Homebrew"
flag --help help="Show help"
flag --installed help="List installed PHP versions"
flag --current help="Show currently active version"
flag --auto help="Auto-switch based on .php-version file"
arg "[version]" help="PHP version (e.g., 7.4, 8.0) or \'latest\'" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_php_switcher.spec"
echo $_usage_spec_php_switcher >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc php-switcher -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc php-switcher -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
