# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/pushover.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in pushover." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_pushover 'name pushover
bin pushover
about "Send Pushover notifications from the command line"
flag -c help="Callback URL" {
    arg <callback>
}
flag -d help="Target device" {
    arg <device>
}
flag -D help="Delivery timestamp" {
    arg <timestamp>
}
flag -e help="Expiration time in seconds" {
    arg <expire>
}
flag -p help="Priority level (-2 to 2)" {
    arg <priority>
}
flag -r help="Retry interval in seconds" {
    arg <retry>
}
flag -t help="Message title" {
    arg <title>
}
flag -T help="Pushover API token" {
    arg <token>
}
flag -s help="Notification sound" {
    arg <sound>
}
flag -u help="URL to include" {
    arg <url>
}
flag -U help="Pushover user key" {
    arg <user>
}
flag -a help="URL title" {
    arg <url_title>
}
arg <message> help="Message content"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_pushover.spec"
echo $_usage_spec_pushover >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc pushover -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc pushover -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
