# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-backup-folder.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-backup-folder." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_backup_folder 'name x-backup-folder
bin x-backup-folder
about "Backup a folder with a timestamp"
arg <folder> help="Folder to backup"
arg "[filename]" help="Custom output filename (default: folder name)" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_backup_folder.spec"
echo $_usage_spec_x_backup_folder >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-backup-folder -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-backup-folder -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
