# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-backup-mysql-with-prefix.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-backup-mysql-with-prefix." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_backup_mysql_with_prefix 'name x-backup-mysql-with-prefix
bin x-backup-mysql-with-prefix
about "Backup MySQL tables matching a prefix"
arg <table_prefix> help="Table name prefix to match"
arg <filename_prefix> help="Output filename prefix"
arg "[database]" help="Database name (optional)" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_backup_mysql_with_prefix.spec"
echo $_usage_spec_x_backup_mysql_with_prefix >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-backup-mysql-with-prefix -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-backup-mysql-with-prefix -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
