# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-change-alacritty-theme.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-change-alacritty-theme." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_change_alacritty_theme 'name x-change-alacritty-theme
bin x-change-alacritty-theme
about "Switch Alacritty color theme"
arg <theme> help="Theme name to apply"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_change_alacritty_theme.spec"
echo $_usage_spec_x_change_alacritty_theme >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-change-alacritty-theme -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-change-alacritty-theme -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
