# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-clean-vendordirs.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-clean-vendordirs." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_clean_vendordirs 'name x-clean-vendordirs
bin x-clean-vendordirs
about "Remove vendor and node_modules directories recursively"
arg "[directory]" help="Directory to clean (default: current)" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_clean_vendordirs.spec"
echo $_usage_spec_x_clean_vendordirs >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-clean-vendordirs -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-clean-vendordirs -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
