# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-compare-versions.py.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-compare-versions.py." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_compare_versions_py 'name x-compare-versions.py
bin x-compare-versions.py
about "Compare semantic version strings"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_compare_versions_py.spec"
echo $_usage_spec_x_compare_versions_py >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-compare-versions.py -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-compare-versions.py -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
