# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-env-list.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-env-list." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_env_list 'name x-env-list
bin x-env-list
about "List environment variables grouped by prefix"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_env_list.spec"
echo $_usage_spec_x_env_list >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-env-list -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-env-list -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
