# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-gh-get-latest-release-targz.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-gh-get-latest-release-targz." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_gh_get_latest_release_targz 'name x-gh-get-latest-release-targz
bin x-gh-get-latest-release-targz
about "Download latest GitHub release tarball"
flag --get help="Download the release"
arg <repo> help="GitHub repository (owner/repo)"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_gh_get_latest_release_targz.spec"
echo $_usage_spec_x_gh_get_latest_release_targz >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-gh-get-latest-release-targz -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-gh-get-latest-release-targz -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
