# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-gh-get-latest-version.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-gh-get-latest-version." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_gh_get_latest_version 'name x-gh-get-latest-version
bin x-gh-get-latest-version
about "Get latest GitHub release version for a repository"
flag --branch help="Get latest branch name"
flag --tag help="Get latest tag (default)"
flag --commit help="Get latest commit SHA"
flag --json help="Output as JSON"
flag "-v --verbose" help="Verbose output"
flag --oldest help="Get oldest instead of latest"
flag --prereleases help="Include pre-releases"
arg <repo> help="GitHub repository (owner/repo)"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_gh_get_latest_version.spec"
echo $_usage_spec_x_gh_get_latest_version >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-gh-get-latest-version -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-gh-get-latest-version -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
