# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-have.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-have." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_have 'name x-have
bin x-have
about "Check if a command exists on the system"
arg <command> help="Command to check for"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_have.spec"
echo $_usage_spec_x_have >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-have -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-have -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
