# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-help.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-help." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_help 'name x-help
bin x-help
about "Browse and display dotfiles documentation"
flag --source-only help="Show raw source instead of rendered output"
arg "[name]" help="Script name to look up (interactive fzf if omitted)" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_help.spec"
echo $_usage_spec_x_help >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-help -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-help -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
