# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-localip.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-localip." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_localip 'name x-localip
bin x-localip
about "Display local IP addresses"
flag --help help="Show help"
flag --version help="Show version"
flag --ipv4 help="Show only IPv4 addresses"
flag --ipv6 help="Show only IPv6 addresses"
arg "[interface]" help="Specific network interface" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_localip.spec"
echo $_usage_spec_x_localip >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-localip -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-localip -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
