# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-multi-ping.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-multi-ping." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_multi_ping 'name x-multi-ping
bin x-multi-ping
about "Multi-protocol ping for IPv4 and IPv6"
flag --help help="Show help"
flag --verbose help="Verbose output"
flag --loop help="Loop indefinitely"
flag --forever help="Loop indefinitely (alias)"
flag --sleep help="Sleep between iterations (default: 1)" {
    arg <seconds>
}
arg <hostnames>… help="Hostnames to ping" var=#true
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_multi_ping.spec"
echo $_usage_spec_x_multi_ping >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-multi-ping -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-multi-ping -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
