# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-path.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-path." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_path 'name x-path
bin x-path
about "Unified PATH manipulation tool"
cmd append help="Append directory to PATH" {
    arg <directory> help="Directory to append"
}
cmd prepend help="Prepend directory to PATH" {
    arg <directory> help="Directory to prepend"
}
cmd remove help="Remove directory from PATH" {
    arg <directory> help="Directory to remove"
}
cmd check help="Check if directory is in PATH" {
    arg <directory> help="Directory to check"
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_path.spec"
echo $_usage_spec_x_path >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-path -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-path -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
