# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-set-php-aliases.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-set-php-aliases." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_set_php_aliases 'name x-set-php-aliases
bin x-set-php-aliases
about "Cache PHP installations and generate shell aliases"
flag --prefix help="Show Homebrew prefix"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_set_php_aliases.spec"
echo $_usage_spec_x_set_php_aliases >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-set-php-aliases -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-set-php-aliases -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
