# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-sha256sum-matcher.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-sha256sum-matcher." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_sha256sum_matcher 'name x-sha256sum-matcher
bin x-sha256sum-matcher
about "Compare two files by SHA256 hash"
flag "-v --verbose" help="Verbose output"
flag "-h --help" help="Show help"
arg <file1> help="First file"
arg <file2> help="Second file"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_sha256sum_matcher.spec"
echo $_usage_spec_x_sha256sum_matcher >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-sha256sum-matcher -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-sha256sum-matcher -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
