# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-sonarcloud.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-sonarcloud." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_sonarcloud 'name x-sonarcloud
bin x-sonarcloud
about "Fetch SonarCloud issues for LLM analysis"
flag --pr help="PR-specific issues" {
    arg <number>
}
flag --branch help="Branch-specific issues" {
    arg <name>
}
flag --org help="Organization name" {
    arg <org>
}
flag --project-key help="Project key" {
    arg <key>
}
flag --severities help="Filter by severity (BLOCKER,CRITICAL,MAJOR,MINOR,INFO)" {
    arg <severities>
}
flag --types help="Filter by type (BUG,VULNERABILITY,CODE_SMELL,SECURITY_HOTSPOT)" {
    arg <types>
}
flag --statuses help="Filter by status (OPEN,CONFIRMED,REOPENED)" {
    arg <statuses>
}
flag --resolved help="Include resolved issues"
flag "-h --help" help="Show help"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_sonarcloud.spec"
echo $_usage_spec_x_sonarcloud >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-sonarcloud -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-sonarcloud -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
