# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-ssl-expiry-date.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-ssl-expiry-date." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_ssl_expiry_date 'name x-ssl-expiry-date
bin x-ssl-expiry-date
about "Check SSL certificate expiry date"
flag -p help="Port number (default: 443)" {
    arg <port>
}
flag -d help="Days threshold for expiry warning" {
    arg <days>
}
arg <hostname> help="Domain or hostname to check"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_ssl_expiry_date.spec"
echo $_usage_spec_x_ssl_expiry_date >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-ssl-expiry-date -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-ssl-expiry-date -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
