# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-thumbgen.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-thumbgen." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_thumbgen 'name x-thumbgen
bin x-thumbgen
about "Generate image thumbnails using ImageMagick"
flag "-h --help" help="Show help"
flag -o help="Output directory (default: same as source)" {
    arg <output_dir>
}
flag -s help="Thumbnail suffix (default: _thumb)" {
    arg <suffix>
}
arg <source_dir> help="Directory containing images"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_thumbgen.spec"
echo $_usage_spec_x_thumbgen >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-thumbgen -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-thumbgen -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
