# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-until-success.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-until-success." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_until_success 'name x-until-success
bin x-until-success
about "Retry a command until it succeeds"
flag --sleep help="Sleep between retries" {
    arg <seconds>
}
flag --help help="Show help"
arg <command>… help="Command to run" var=#true
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_until_success.spec"
echo $_usage_spec_x_until_success >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-until-success -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-until-success -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
