# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-visit-folders.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-visit-folders." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_visit_folders 'name x-visit-folders
bin x-visit-folders
about "Register subdirectories with zoxide"
flag --dry-run help="Show what would be registered"
flag --verbose help="Verbose output"
flag --help help="Show help"
arg "[directory]" help="Target directory (default: current)" required=#false
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_visit_folders.spec"
echo $_usage_spec_x_visit_folders >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-visit-folders -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-visit-folders -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
