# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-when-up.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &>/dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in x-when-up." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_x_when_up 'name x-when-up
bin x-when-up
about "Wait for host to come online, then execute command"
arg <host> help="Host to monitor"
arg <command>… help="Command to execute when host is up" var=#true
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_x_when_up.spec"
echo $_usage_spec_x_when_up >"$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc x-when-up -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc x-when-up -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
