#compdef cleanup-old-version-managers.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/cleanup-old-version-managers.sh.usage.kdl
local curcontext="$curcontext"

_cleanup_old_version_managers_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in cleanup-old-version-managers.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_cleanup_old_version_managers_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name cleanup-old-version-managers.sh
bin cleanup-old-version-managers.sh
about "Remove old version manager installations (nvm, fnm, pyenv, goenv)"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_cleanup_old_version_managers_sh" ]; then
  _cleanup_old_version_managers_sh "$@"
else
  compdef _cleanup_old_version_managers_sh cleanup-old-version-managers.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
