#compdef create-wezterm-keymaps.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/create-wezterm-keymaps.sh.usage.kdl
local curcontext="$curcontext"

_create_wezterm_keymaps_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in create-wezterm-keymaps.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_create_wezterm_keymaps_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name create-wezterm-keymaps.sh
bin create-wezterm-keymaps.sh
about "Generate WezTerm keybindings documentation"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_create_wezterm_keymaps_sh" ]; then
  _create_wezterm_keymaps_sh "$@"
else
  compdef _create_wezterm_keymaps_sh create-wezterm-keymaps.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
