#compdef install-fonts.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/install-fonts.sh.usage.kdl
local curcontext="$curcontext"

_install_fonts_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in install-fonts.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_install_fonts_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name install-fonts.sh
bin install-fonts.sh
about "Install programming fonts from GitHub releases"
flag --force help="Re-download and reinstall all fonts"
flag --help help="Show help"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_install_fonts_sh" ]; then
  _install_fonts_sh "$@"
else
  compdef _install_fonts_sh install-fonts.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
