#compdef install-completions.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/install-completions.sh.usage.kdl
local curcontext="$curcontext"

_install_completions_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in install-completions.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_install_completions_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name install-completions.sh
bin install-completions.sh
about "Generate shell completions, markdown docs, and manpages from usage specs"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_install_completions_sh" ]; then
  _install_completions_sh "$@"
else
  compdef _install_completions_sh install-completions.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
