#compdef shared.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/shared.sh.usage.kdl
local curcontext="$curcontext"

_shared_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in shared.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_shared_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name shared.sh
bin shared.sh
about "Shared bash functions and helpers for install scripts"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_shared_sh" ]; then
  _shared_sh "$@"
else
  compdef _shared_sh shared.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
