#compdef update-readme-aliases.sh
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/scripts/update-readme-aliases.sh.usage.kdl
local curcontext="$curcontext"

_update_readme_aliases_sh()
{
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in update-readme-aliases.sh." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_update_readme_aliases_sh.spec"
  cat >| "$spec_file" << '__USAGE_EOF__'
name update-readme-aliases.sh
bin update-readme-aliases.sh
about "Update alias documentation in docs/alias.md"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_update_readme_aliases_sh" ]; then
  _update_readme_aliases_sh "$@"
else
  compdef _update_readme_aliases_sh update-readme-aliases.sh
fi

# vim: noet ci pi sts=0 sw=4 ts=4
