#compdef x-compare-versions.py
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-compare-versions.py.usage.kdl
local curcontext="$curcontext"

_x_compare_versions_py() {
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work in x-compare-versions.py." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_compare_versions_py.spec"
  cat >| "$spec_file" <<'__USAGE_EOF__'
name x-compare-versions.py
bin x-compare-versions.py
about "Compare semantic version strings"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_x_compare_versions_py" ]; then
    _x_compare_versions_py "$@"
else
    compdef _x_compare_versions_py x-compare-versions.py
fi

# vim: noet ci pi sts=0 sw=4 ts=4
