#compdef x-multi-ping.pl
# @generated by usage-cli from /Users/ivuorinen/.dotfiles/local/bin/x-multi-ping.pl.usage.kdl
local curcontext="$curcontext"

_x_multi_ping_pl() {
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work in x-multi-ping.pl." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_x_multi_ping_pl.spec"
  cat >| "$spec_file" <<'__USAGE_EOF__'
name x-multi-ping.pl
bin x-multi-ping.pl
about "Multi-protocol ping utility (Perl version)"
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_x_multi_ping_pl" ]; then
    _x_multi_ping_pl "$@"
else
    compdef _x_multi_ping_pl x-multi-ping.pl
fi

# vim: noet ci pi sts=0 sw=4 ts=4
