# Lakka zsh configuration.
#
# shellcheck shell=bash
export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/usr/sbin:$PATH"

# Defaults
export DOTFILES="$HOME/.dotfiles"

# Run x-load-configs in your terminal to reload the files.
function x-load-configs()
{
    # Load the shell dotfiles, and then some:
    for file in $DOTFILES/config/{exports,alias,functions}; do
        [ -r "$file" ] && [ -f "$file" ] && source "$file"
        [ -r "$file-secret" ] && [ -f "$file-secret" ] && source "$file-secret"
        [ -r "$file-$HOSTNAME" ] && [ -f "$file-$HOSTNAME" ] && source "$file-$HOSTNAME"
        [ -r "$file-$HOSTNAME-secret" ] && [ -f "$file-$HOSTNAME-secret" ] && source "$file-$HOSTNAME-secret"
    done
}
x-load-configs

export PATH="$XDG_BIN_HOME:$PATH"
export LC_ALL=fi_FI.utf8

export RVM_PATH="$HOME/.rvm"
export PATH="$RVM_PATH/bin:$PATH"
[[ -s "$RVM_PATH/scripts/rvm" ]] && source "$RVM_PATH/scripts/rvm" # Load RVM into a shell session *as a function*

# Try to load antigen, if present
ANTIGEN_ZSH_PATH="$XDG_BIN_HOME/antigen.zsh"
[[ -f "$ANTIGEN_ZSH_PATH" ]] && source "$ANTIGEN_ZSH_PATH"

# If antigen was loaded
if command -v antigen &> /dev/null; then
  antigen use oh-my-zsh

  # config/functions
  x-default-antigen-bundles

  antigen theme oskarkrawczyk/honukai-iterm-zsh honukai

  antigen apply
fi

alias logrotate='/usr/sbin/logrotate -s $HOME/logs/state'
alias nano='nano -wS -$'
alias gpg=gpg2

ACME_PATH="$HOME/.acme.sh"
[[ -s "$ACME_PATH/acme.sh.env" ]] && . "$ACME_PATH/acme.sh.env"
