# Lakka zsh configuration.
#
# shellcheck shell=bash
export PATH="/usr/local/bin:/usr/bin:/usr/sbin:$PATH"

# Defaults
export DOTFILES="$HOME/.dotfiles"

# Run x-load-configs in your terminal to reload the files.
function x-load-configs()
{
    # Load the shell dotfiles, and then some:
    for file in $DOTFILES/config/{exports,alias,functions}; do
        [ -r "$file" ] && [ -f "$file" ] && source "$file"
        [ -r "$file-secret" ] && [ -f "$file-secret" ] && source "$file-secret"
        [ -r "$file-$HOSTNAME" ] && [ -f "$file-$HOSTNAME" ] && source "$file-$HOSTNAME"
        [ -r "$file-$HOSTNAME-secret" ] && [ -f "$file-$HOSTNAME-secret" ] && source "$file-$HOSTNAME-secret"
    done
}
x-load-configs

export PATH="$XDG_BIN_HOME:$HOME/bin:$HOME/.rvm/bin:$PATH"
export LC_ALL=fi_FI.utf8

# Try to load antigen, if present
[[ -f "$XDG_BIN_HOME/antigen.zsh" ]] && source "$XDG_BIN_HOME/antigen.zsh"

# If antigen was loaded
if command -v antigen &> /dev/null; then
  antigen use oh-my-zsh

  antigen bundle ssh-agent
  antigen bundle colored-man-pages
  antigen bundle jreese/zsh-titles
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-completions
  antigen bundle MichaelAquilina/zsh-you-should-use
  antigen bundle unixorn/autoupdate-antigen.zshplugin
  antigen bundle Sparragus/zsh-auto-nvm-use
  antigen bundle autojump
  antigen bundle command-not-found
  antigen bundle unixorn/rvm-plugin

  hash git 2>/dev/null && antigen bundle git
  hash php 2>/dev/null && antigen bundle php
  hash python 2>/dev/null && antigen bundle MichaelAquilina/zsh-autoswitch-virtualenv
  hash jq 2>/dev/null && antigen bundle reegnz/jq-zsh-plugin
  hash docker-compose 2>/dev/null && antigen bundle sroze/docker-compose-zsh-plugin

  antigen theme oskarkrawczyk/honukai-iterm-zsh honukai

  antigen apply
fi

alias logrotate='/usr/sbin/logrotate -s $HOME/logs/state'
alias nano='nano -wS -$'
alias gpg=gpg2

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" ]] # Load RVM into a shell session *as a function*
. "$HOME/.acme.sh/acme.sh.env"
