.TH GIT-ATTRIBUTES 1
.SH NAME
git\-attributes \- Check .gitattributes coverage and suggest missing rules
.SH SYNOPSIS
\fBgit\-attributes\fR [OPTIONS]
.SH DESCRIPTION
Check .gitattributes coverage and suggest missing rules
.PP
.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Show help
.TP
\fB\-v, \-\-verbose\fR
Verbose output
.TP
\fB\-e, \-\-exit\fR
Exit with error if uncovered files found
.TP
\fB\-p, \-\-pattern\fR
Show pattern matches
.TP
\fB\-n, \-\-no\-suggest\fR
Skip suggestions
.TP
\fB\-w, \-\-write\fR
Write suggested rules to .gitattributes
.TP
\fB\-f, \-\-format\-width\fR \fI<width>\fR
Format column width
