.TH GIT-UPDATE-DIRS 1
.SH NAME
git\-update\-dirs \- Pull and rebase all git repos in subdirectories
.SH SYNOPSIS
\fBgit\-update\-dirs\fR [OPTIONS]
.SH DESCRIPTION
Pull and rebase all git repos in subdirectories
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Display help
.TP
\fB\-\-version\fR
Display version
.TP
\fB\-v, \-\-verbose\fR
Verbose output
.TP
\fB\-q, \-\-quiet\fR
Quiet output
.TP
\fB\-\-force\fR
Force operations
