.TH INSTALL-FONTS.SH 1
.SH NAME
install\-fonts.sh \- Install programming fonts from GitHub releases
.SH SYNOPSIS
\fBinstall\-fonts.sh\fR [OPTIONS]
.SH DESCRIPTION
Install programming fonts from GitHub releases
.PP
.SH OPTIONS
.TP
\fB\-\-force\fR
Re\-download and reinstall all fonts
.TP
\fB\-\-help\fR
Show help
