.TH PHP-SWITCHER 1
.SH NAME
php\-switcher \- Switch between PHP versions installed via Homebrew
.SH SYNOPSIS
\fBphp\-switcher\fR [OPTIONS] [<version>]
.SH DESCRIPTION
Switch between PHP versions installed via Homebrew
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Show help
.TP
\fB\-\-installed\fR
List installed PHP versions
.TP
\fB\-\-current\fR
Show currently active version
.TP
\fB\-\-auto\fR
Auto\-switch based on .php\-version file
.SH ARGUMENTS
.TP
\fB<version>\fR
PHP version (e.g., 7.4, 8.0) or 'latest'
