.TH PUSHOVER 1
.SH NAME
pushover \- Send Pushover notifications from the command line
.SH SYNOPSIS
\fBpushover\fR [OPTIONS] <message>
.SH DESCRIPTION
Send Pushover notifications from the command line
.PP
.SH OPTIONS
.TP
\fB\-c\fR \fI<callback>\fR
Callback URL
.TP
\fB\-d\fR \fI<device>\fR
Target device
.TP
\fB\-D\fR \fI<timestamp>\fR
Delivery timestamp
.TP
\fB\-e\fR \fI<expire>\fR
Expiration time in seconds
.TP
\fB\-p\fR \fI<priority>\fR
Priority level (\-2 to 2)
.TP
\fB\-r\fR \fI<retry>\fR
Retry interval in seconds
.TP
\fB\-t\fR \fI<title>\fR
Message title
.TP
\fB\-T\fR \fI<token>\fR
Pushover API token
.TP
\fB\-s\fR \fI<sound>\fR
Notification sound
.TP
\fB\-u\fR \fI<url>\fR
URL to include
.TP
\fB\-U\fR \fI<user>\fR
Pushover user key
.TP
\fB\-a\fR \fI<url_title>\fR
URL title
.SH ARGUMENTS
.TP
\fB<message>\fR
Message content
