.TH X-BACKUP-MYSQL-WITH-PREFIX 1
.SH NAME
x\-backup\-mysql\-with\-prefix \- Backup MySQL tables matching a prefix
.SH SYNOPSIS
\fBx\-backup\-mysql\-with\-prefix\fR <table_prefix> <filename_prefix> [<database>]
.SH DESCRIPTION
Backup MySQL tables matching a prefix
.PP
.SH ARGUMENTS
.TP
\fB<table_prefix>\fR
Table name prefix to match
.TP
\fB<filename_prefix>\fR
Output filename prefix
.TP
\fB<database>\fR
Database name (optional)
