.TH X-BACKUP-FOLDER 1
.SH NAME
x\-backup\-folder \- Backup a folder with a timestamp
.SH SYNOPSIS
\fBx\-backup\-folder\fR <folder> [<filename>]
.SH DESCRIPTION
Backup a folder with a timestamp
.PP
.SH ARGUMENTS
.TP
\fB<folder>\fR
Folder to backup
.TP
\fB<filename>\fR
Custom output filename (default: folder name)
