.TH X-CLEAN-VENDORDIRS 1
.SH NAME
x\-clean\-vendordirs \- Remove vendor and node_modules directories recursively
.SH SYNOPSIS
\fBx\-clean\-vendordirs\fR [<directory>]
.SH DESCRIPTION
Remove vendor and node_modules directories recursively
.PP
.SH ARGUMENTS
.TP
\fB<directory>\fR
Directory to clean (default: current)
