.TH X-CODEQL 1
.SH NAME
x\-codeql \- CodeQL security scanning wrapper
.SH SYNOPSIS
\fBx\-codeql\fR [OPTIONS]
.SH DESCRIPTION
CodeQL security scanning wrapper
.PP
.SH OPTIONS
.TP
\fB\-\-path\fR \fI<path>\fR
Source path to analyze (default: current directory)
.TP
\fB\-\-parallel\fR
Run language analyses in parallel
.TP
\fB\-h, \-\-help\fR
Show help
.TP
\fB\-v, \-\-version\fR
Show version
