.TH X-FOREACH 1
.SH NAME
x\-foreach \- Run a command in each directory from a listing
.SH SYNOPSIS
\fBx\-foreach\fR <listing_cmd> <command> ...
.SH DESCRIPTION
Run a command in each directory from a listing
.PP
.SH ARGUMENTS
.TP
\fB<listing_cmd>\fR
Command that lists directories
.TP
\fB<command>\fR
Command to run in each directory
