.TH X-GH-GET-LATEST-RELEASE-TARGZ 1
.SH NAME
x\-gh\-get\-latest\-release\-targz \- Download latest GitHub release tarball
.SH SYNOPSIS
\fBx\-gh\-get\-latest\-release\-targz\fR [OPTIONS] <repo>
.SH DESCRIPTION
Download latest GitHub release tarball
.PP
.SH OPTIONS
.TP
\fB\-\-get\fR
Download the release
.SH ARGUMENTS
.TP
\fB<repo>\fR
GitHub repository (owner/repo)
