.TH X-HELP 1
.SH NAME
x\-help \- Browse and display dotfiles documentation
.SH SYNOPSIS
\fBx\-help\fR [OPTIONS] [<name>]
.SH DESCRIPTION
Browse and display dotfiles documentation
.PP
.SH OPTIONS
.TP
\fB\-\-source\-only\fR
Show raw source instead of rendered output
.SH ARGUMENTS
.TP
\fB<name>\fR
Script name to look up (interactive fzf if omitted)
