.TH X-LOCALIP 1
.SH NAME
x\-localip \- Display local IP addresses
.SH SYNOPSIS
\fBx\-localip\fR [OPTIONS] [<interface>]
.SH DESCRIPTION
Display local IP addresses
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Show help
.TP
\fB\-\-version\fR
Show version
.TP
\fB\-\-ipv4\fR
Show only IPv4 addresses
.TP
\fB\-\-ipv6\fR
Show only IPv6 addresses
.SH ARGUMENTS
.TP
\fB<interface>\fR
Specific network interface
