.TH X-MULTI-PING 1
.SH NAME
x\-multi\-ping \- Multi\-protocol ping for IPv4 and IPv6
.SH SYNOPSIS
\fBx\-multi\-ping\fR [OPTIONS] <hostnames> ...
.SH DESCRIPTION
Multi\-protocol ping for IPv4 and IPv6
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Show help
.TP
\fB\-\-verbose\fR
Verbose output
.TP
\fB\-\-loop\fR
Loop indefinitely
.TP
\fB\-\-forever\fR
Loop indefinitely (alias)
.TP
\fB\-\-sleep\fR \fI<seconds>\fR
Sleep between iterations (default: 1)
.SH ARGUMENTS
.TP
\fB<hostnames>\fR
Hostnames to ping
