.TH X-PATH 1
.SH NAME
x\-path \- Unified PATH manipulation tool
.SH SYNOPSIS
\fBx\-path\fR [COMMAND]
.SH DESCRIPTION
Unified PATH manipulation tool
.PP
.SH COMMANDS
.TP
\fBappend\fR
Append directory to PATH
.TP
\fBprepend\fR
Prepend directory to PATH
.TP
\fBremove\fR
Remove directory from PATH
.TP
\fBcheck\fR
Check if directory is in PATH
.SH "X-PATH APPEND"
Append directory to PATH
.PP
\fBUsage:\fR x\-path append <directory>
.PP
\fBArguments:\fR
.PP
.TP
\fB<directory>\fR
Directory to append
.SH "X-PATH PREPEND"
Prepend directory to PATH
.PP
\fBUsage:\fR x\-path prepend <directory>
.PP
\fBArguments:\fR
.PP
.TP
\fB<directory>\fR
Directory to prepend
.SH "X-PATH REMOVE"
Remove directory from PATH
.PP
\fBUsage:\fR x\-path remove <directory>
.PP
\fBArguments:\fR
.PP
.TP
\fB<directory>\fR
Directory to remove
.SH "X-PATH CHECK"
Check if directory is in PATH
.PP
\fBUsage:\fR x\-path check <directory>
.PP
\fBArguments:\fR
.PP
.TP
\fB<directory>\fR
Directory to check
