.TH X-PR-COMMENTS 1
.SH NAME
x\-pr\-comments \- Fetch PR comments formatted for LLM analysis
.SH SYNOPSIS
\fBx\-pr\-comments\fR [OPTIONS] <pr>
.SH DESCRIPTION
Fetch PR comments formatted for LLM analysis
.PP
.SH OPTIONS
.TP
\fB\-\-help\fR
Show help
.SH ARGUMENTS
.TP
\fB<pr>\fR
PR number or full GitHub URL
