.TH X-SHA256SUM-MATCHER 1
.SH NAME
x\-sha256sum\-matcher \- Compare two files by SHA256 hash
.SH SYNOPSIS
\fBx\-sha256sum\-matcher\fR [OPTIONS] <file1> <file2>
.SH DESCRIPTION
Compare two files by SHA256 hash
.PP
.SH OPTIONS
.TP
\fB\-v, \-\-verbose\fR
Verbose output
.TP
\fB\-h, \-\-help\fR
Show help
.SH ARGUMENTS
.TP
\fB<file1>\fR
First file
.TP
\fB<file2>\fR
Second file
