.TH X-SSL-EXPIRY-DATE 1
.SH NAME
x\-ssl\-expiry\-date \- Check SSL certificate expiry date
.SH SYNOPSIS
\fBx\-ssl\-expiry\-date\fR [OPTIONS] <hostname>
.SH DESCRIPTION
Check SSL certificate expiry date
.PP
.SH OPTIONS
.TP
\fB\-p\fR \fI<port>\fR
Port number (default: 443)
.TP
\fB\-d\fR \fI<days>\fR
Days threshold for expiry warning
.SH ARGUMENTS
.TP
\fB<hostname>\fR
Domain or hostname to check
