.TH X-THUMBGEN 1
.SH NAME
x\-thumbgen \- Generate image thumbnails using ImageMagick
.SH SYNOPSIS
\fBx\-thumbgen\fR [OPTIONS] <source_dir>
.SH DESCRIPTION
Generate image thumbnails using ImageMagick
.PP
.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Show help
.TP
\fB\-o\fR \fI<output_dir>\fR
Output directory (default: same as source)
.TP
\fB\-s\fR \fI<suffix>\fR
Thumbnail suffix (default: _thumb)
.SH ARGUMENTS
.TP
\fB<source_dir>\fR
Directory containing images
