.TH X-UNTIL-SUCCESS 1
.SH NAME
x\-until\-success \- Retry a command until it succeeds
.SH SYNOPSIS
\fBx\-until\-success\fR [OPTIONS] <command> ...
.SH DESCRIPTION
Retry a command until it succeeds
.PP
.SH OPTIONS
.TP
\fB\-\-sleep\fR \fI<seconds>\fR
Sleep between retries
.TP
\fB\-\-help\fR
Show help
.SH ARGUMENTS
.TP
\fB<command>\fR
Command to run
