.TH X-UNTIL-ERROR 1
.SH NAME
x\-until\-error \- Run a command repeatedly until it fails
.SH SYNOPSIS
\fBx\-until\-error\fR [OPTIONS] <command> ...
.SH DESCRIPTION
Run a command repeatedly until it fails
.PP
.SH OPTIONS
.TP
\fB\-\-sleep\fR \fI<seconds>\fR
Sleep between iterations
.TP
\fB\-\-help\fR
Show help
.SH ARGUMENTS
.TP
\fB<command>\fR
Command to run
