.TH X-VISIT-FOLDERS 1
.SH NAME
x\-visit\-folders \- Register subdirectories with zoxide
.SH SYNOPSIS
\fBx\-visit\-folders\fR [OPTIONS] [<directory>]
.SH DESCRIPTION
Register subdirectories with zoxide
.PP
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR
Show what would be registered
.TP
\fB\-\-verbose\fR
Verbose output
.TP
\fB\-\-help\fR
Show help
.SH ARGUMENTS
.TP
\fB<directory>\fR
Target directory (default: current)
