.TH X-WHEN-UP 1
.SH NAME
x\-when\-up \- Wait for host to come online, then execute command
.SH SYNOPSIS
\fBx\-when\-up\fR <host> <command> ...
.SH DESCRIPTION
Wait for host to come online, then execute command
.PP
.SH ARGUMENTS
.TP
\fB<host>\fR
Host to monitor
.TP
\fB<command>\fR
Command to execute when host is up
