---
# $schema: "https://json.schemastore.org/github-workflow.json"
name: Pre-commit autoupdate

on:
  schedule:
    # At 04:00 on Monday and Thursday.
    - cron: "0 4 * * 1,4"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  auto-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0

      - run: pip install pre-commit==4.2.0 && pre-commit autoupdate

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: "chore: update pre-commit hooks"
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
