---
# $schema: "https://json.schemastore.org/github-workflow.json"
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-labels.yml
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  SyncLabels:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: ivuorinen/actions/sync-labels@0795e029fb0083fe692fb10b4ed6132822b069e6 # v2026.04.06
